using StudioBookingSystem.EntityFrameworkCore;
using Xunit;

namespace StudioBookingSystem.EntityFrameworkCore;

public class StudioBookingSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<StudioBookingSystemEntityFrameworkCoreFixture>
{

}
